### ISSUE TITLE
Implement timestamp variable

### ISSUE THREAD

**Issue by SamMousa** [collecthor/surveyjs-parser#65]
A variable that implements the new interface from this: https://github.com/collecthor/data-interfaces/issues/4

The text parser should use this for certain input types like `datetime`, `datetime-local` and `date`.

We should decide if handling is needed for timezones. (it might not be since the inputs always submit in UTC iirc)

**Comment by radwouters** [comment]
I do not think that timezone handling is both possible and needed.

For timezone handling, it would be necessary to include the timezone of the person taking the survey somewhere, which is not a default feature of SurveyJS IIRC.

Furthermore, the `datetime-local` and `date` questions are a completely manual input by the person taking the survey, for asking questions such as "when did you purchase this item".  This is not converted to UTC, but I do not see much cases where conversion to UTC would be needed in a survey.

**Comment by SamMousa** [comment]
Oh yes, I got confused and thought there was a timezone conversion, but it just applies a standard format to the submitted value.
